
import { 
  ToolsIcon, 
  ScreenIcon, 
  BatteryIcon, 
  MotherboardIcon, 
  SolderingIcon, 
  SoftwareIcon,
  IosIcon,
  AndroidIcon,
  ConnectorIcon
} from './components/IconComponents';
import type { Course } from './types';

export const courses: Course[] = [
  {
    id: 'intro',
    title: 'Introdução e Ferramentas',
    description: 'Comece sua jornada com o pé direito. Conheça as ferramentas essenciais e os conceitos básicos de segurança.',
    longDescription: 'Bem-vindo ao ponto de partida da sua jornada como técnico de manutenção de celulares. Este módulo inicial foi desenhado para desmistificar o processo de reparo, apresentando os conceitos fundamentais de segurança e a organização de uma bancada de trabalho eficiente. Você entenderá a importância de cada passo, desde a correta identificação dos problemas até a execução dos procedimentos com precisão e segurança, garantindo a integridade dos aparelhos e a sua.',
    icon: ToolsIcon,
    topics: [
      'Kit de Chaves de Precisão: Indispensável para abrir os parafusos específicos de cada marca, como Philips, Pentalobe (iPhone) e Torx.',
      'Espátulas Plásticas e Metálicas: Utilizadas para abrir carcaças e desconectar componentes delicados sem causar arranhões ou danos.',
      'Ventosa de Sucção: Ferramenta chave para remover telas de vidro com segurança, aplicando uma força de tração uniforme.',
      'Estação de Ar Quente (Retrabalho): Essencial para dessoldar e soldar componentes na placa-mãe, como conectores de carga e CIs.',
      'Fonte de Alimentação Assimétrica: Permite ligar a placa-mãe sem a bateria para diagnosticar curtos-circuitos e analisar o consumo de energia.',
      'Multímetro Digital: Ferramenta de diagnóstico fundamental para medir voltagem, corrente e continuidade em circuitos eletrônicos.',
      'Pinças de Precisão (Reta e Curva): Usadas para manipular componentes minúsculos, parafusos e cabos flexíveis com exatidão.',
      'Manta Antiestática (ESD): Protege os componentes eletrônicos sensíveis contra danos por descarga eletrostática durante o manuseio.',
      'Pulseira e Luvas Antiestáticas (ESD): Equipamento de proteção pessoal que aterra o técnico para evitar que a eletricidade estática do corpo danifique o aparelho.',
      'Álcool Isopropílico: O solvente ideal para limpar placas de circuito e componentes eletrônicos, pois evapora rapidamente sem deixar resíduos.',
      'Microscópio USB ou Estereoscópio: Amplia a visão da placa-mãe, permitindo a execução de micro-soldagens e a inspeção de componentes minúsculos.',
      'Cuba Ultrassônica para Desoxidação: Utilizada com produtos químicos específicos para remover a oxidação de placas que tiveram contato com líquidos.',
    ],
  },
  {
    id: 'screen',
    title: 'Reparo de Telas e Displays',
    description: 'Aprenda a trocar telas quebradas de diversos modelos, dos mais simples aos mais complexos.',
    longDescription: 'Um dos serviços mais comuns e lucrativos na manutenção de celulares. Este módulo foca em todo o processo de substituição de telas, desde a avaliação inicial até os testes finais. Você aprenderá as técnicas corretas para lidar com diferentes tecnologias de display, como LCD e OLED, e os cuidados necessários para realizar um trabalho limpo e profissional, garantindo a satisfação total do seu cliente.',
    icon: ScreenIcon,
    topics: [
      'Diagnóstico Inicial: Antes de desmontar, teste todas as funções do aparelho (câmeras, microfone, botões) para garantir que o único problema é a tela.',
      'Preparação da Bancada: Organize suas ferramentas e utilize uma manta magnética para não perder os parafusos. Tenha a tela nova em mãos para comparação.',
      'Aquecimento e Abertura: Aqueça as bordas do aparelho (entre 80-100°C) com uma estação de ar quente ou separadora para amolecer a cola. Use uma ventosa e espátulas plásticas para abrir o chassi com cuidado.',
      'Desconexão de Componentes: Desconecte a bateria primeiro para evitar curtos-circuitos. Em seguida, com cuidado, desconecte os cabos flexíveis (flex cables) da tela, biometria e outros sensores.',
      'Remoção da Tela Antiga: Com o aparelho aberto, remova cuidadosamente a tela danificada. Limpe toda a cola antiga e resíduos de vidro do chassi para garantir um encaixe perfeito da nova tela.',
      'Teste da Tela Nova (Pré-colagem): Conecte a nova tela temporariamente (sem colar) e ligue o aparelho. Teste o touch em toda a superfície, as cores, o brilho e a resposta do display.',
      'Colagem e Montagem: Após o teste, aplique a cola específica (como B-7000 ou T-7000) nas bordas do chassi. Encaixe a nova tela, reconecte todos os cabos e a bateria.',
      'Fechamento e Testes Finais: Feche o aparelho, coloque os parafusos e utilize presilhas ou elásticos para pressionar a tela enquanto a cola seca (por pelo menos 4 horas). Realize um teste completo de todas as funções novamente.',
    ],
  },
  {
    id: 'battery',
    title: 'Troca e Diagnóstico de Bateria',
    description: 'Domine a arte de substituir baterias e diagnosticar problemas de carregamento e autonomia.',
    longDescription: 'Baterias são o coração energético do celular, mas têm uma vida útil limitada. Este módulo essencial ensina tudo sobre elas: desde identificar os sinais de uma bateria cansada ou defeituosa até o procedimento de troca seguro e eficaz. Domine esta habilidade crucial e resolva um dos problemas mais frequentes enfrentados pelos usuários.',
    icon: BatteryIcon,
    topics: [
      '**Como Trocar a Bateria (Passo a Passo):**',
      '1. **Diagnóstico:** Verifique a "Saúde da Bateria" nas configurações (iOS) ou use apps de diagnóstico (Android) para confirmar a necessidade da troca.',
      '2. **Abertura do Aparelho:** Aqueça a tampa traseira para amolecer o adesivo. Use ventosas e espátulas para abrir o dispositivo com cuidado.',
      '3. **Desconexão Segura:** A primeira coisa a fazer é desconectar o cabo flex da bateria da placa-mãe para desenergizar o circuito e evitar curtos.',
      '4. **Remoção da Bateria Antiga:** As baterias são fixadas com adesivos fortes. Use álcool isopropílico para dissolver a cola e uma espátula plástica (nunca de metal) para removê-la com cuidado, sem dobrar ou perfurar.',
      '5. **Instalação e Fechamento:** Limpe a área, aplique novas fitas adesivas, posicione a nova bateria, conecte-a e monte o aparelho.',
      '6. **Calibração:** Após a troca, use o celular até a bateria descarregar completamente e depois realize uma carga completa até 100% sem interrupções.',
      '**Principais Defeitos e Dicas:**',
      '- **Bateria Estufada:** Sinal de falha grave. Causa pressão na tela e na carcaça. Remova com extremo cuidado, pois há risco de incêndio se perfurada.',
      '- **Desligamentos Súbitos:** O celular desliga mesmo com carga (ex: 30-40%). A bateria não consegue mais fornecer a corrente necessária.',
      '- **Não Carrega ou Carregamento Lento:** Antes de culpar a bateria, sempre teste com outro cabo e carregador. O defeito também pode ser no conector de carga.',
      '- **Superaquecimento:** Baterias defeituosas podem esquentar excessivamente. A troca é uma medida de segurança para evitar danos a outros componentes.',
    ],
  },
  {
    id: 'motherboard',
    title: 'Diagnóstico de Placa-mãe',
    description: 'Aprenda a ler esquemas elétricos e a diagnosticar defeitos complexos na placa-mãe.',
    longDescription: 'Entre no nível mais avançado da manutenção. A placa-mãe é o cérebro do celular, e entender seu funcionamento é o que diferencia um técnico comum de um especialista. Este módulo ensina a diagnosticar e reparar falhas em nível de componente, abrindo portas para os consertos mais desafiadores e lucrativos.',
    icon: MotherboardIcon,
    topics: [
      '**Principais Defeitos e Diagnósticos:**',
      '- **Curto-circuito:** Identifique a causa do consumo excessivo de corrente usando a fonte de alimentação e técnicas de congelamento (breu) ou câmera térmica.',
      '- **Danos por Líquido (Oxidação):** Aprenda o processo correto de desoxidação com cuba ultrassônica e a identificar componentes corroídos que precisam ser substituídos.',
      '- **Aparelho Não Liga:** Siga uma linha de diagnóstico, verificando o botão power, o circuito de carga (PMIC) e as tensões primárias.',
      '- **Falhas de Backlight (Tela Escura):** Analise o circuito que alimenta a iluminação da tela, incluindo o CI de backlight, diodos e bobinas.',
      '**Como Trocar Componentes (Micro-soldagem):**',
      '1. **Isolamento da Área:** Proteja os componentes ao redor do alvo com fita Kapton (resistente ao calor) para evitar danos.',
      '2. **Aplicação de Fluxo:** Aplique fluxo de solda de boa qualidade sobre o componente. Isso ajuda na transferência de calor e evita a oxidação.',
      '3. **Dessoldagem (Ar Quente):** Com a estação de ar quente (aprox. 380-420°C), aqueça o componente em movimentos circulares até a solda fundir. Remova-o com uma pinça.',
      '4. **Limpeza dos Pads:** Com a malha dessoldadora e o ferro de solda, remova a solda antiga dos contatos (pads) na placa. Limpe a área com álcool isopropílico.',
      '5. **Soldagem do Novo Componente:** Posicione o novo componente e aqueça novamente com a estação de ar quente até que ele se "assente" nos pads. Dê um leve toque para confirmar a fusão.',
      '6. **Inspeção Final:** Após esfriar, inspecione a solda com um microscópio para garantir que não há curtos. Limpe o fluxo residual.',
    ],
  },
  {
    id: 'connectors',
    title: 'Reparo de Conectores',
    description: 'Especialize-se na troca de conectores de carga, fone de ouvido e outros componentes.',
    longDescription: 'Problemas de carregamento são uma das queixas mais comuns. Dominar a troca de conectores (USB-C, Lightning, Micro-USB) é uma habilidade essencial e altamente rentável. Este módulo ensina as técnicas de micro-soldagem necessárias para realizar um trabalho limpo e duradouro, garantindo que o aparelho do cliente volte a carregar e transferir dados perfeitamente.',
    icon: ConnectorIcon,
    topics: [
      '**Como Trocar Conectores (Passo a Passo):**',
      '1. **Diagnóstico:** Antes de tudo, limpe o conector com uma escova e álcool isopropílico. Teste com um cabo e carregador sabidamente bons. O problema pode ser sujeira ou um acessório defeituoso.',
      '2. **Proteção:** Isole a área ao redor do conector com fita Kapton. Isso protegerá microfones, plásticos e outros componentes sensíveis do calor da estação de ar quente.',
      '3. **Facilitando a Remoção:** Aplique fluxo de solda e um pouco de solda de baixa fusão (como 183°C) sobre os pinos do conector antigo. Isso ajuda a remover o componente sem exigir calor excessivo na placa.',
      '4. **Dessoldagem:** Use a estação de ar quente por baixo da placa (se possível) ou por cima com cuidado. Aqueça a área até a solda brilhar e remova o conector defeituoso com uma pinça.',
      '5. **Limpeza e Preparação:** Com malha dessoldadora, remova toda a solda antiga dos pads (pontos de contato). Limpe a área com álcool isopropílico para não deixar nenhum resíduo.',
      '6. **Estanhagem dos Pads:** Aplique fluxo e passe um pouco de solda nova em cada pad na placa. Isso prepara a base para receber o novo componente.',
      '7. **Soldagem do Novo Conector:** Posicione o novo conector. Solde primeiro os pinos de ancoragem (laterais) para fixá-lo. Depois, com um ferro de solda de ponta fina, solde cada um dos pinos de dados e energia individualmente.',
      '8. **Inspeção e Teste Final:** Com um microscópio, verifique se não há curtos entre os pinos. Faça uma limpeza final. Antes de fechar o aparelho, conecte uma bateria e um cabo para testar se o carregamento e a transferência de dados estão funcionando.',
    ]
  },
  {
    id: 'microsoldering',
    title: 'Micro-soldagem Avançada',
    description: 'Leve suas habilidades ao próximo nível com técnicas de micro-soldagem para reparos em nível de componente.',
    longDescription: 'Esta é a habilidade que separa os profissionais de elite. A micro-soldagem permite reparar o que outros condenam, trabalhando diretamente em Circuitos Integrados (CIs) e componentes minúsculos. Aprenda as técnicas de precisão com microscópio, estação de ar quente e ferro de solda para realizar os reparos mais complexos e lucrativos do mercado.',
    icon: SolderingIcon,
    topics: [
      '**Como Fazer Reballing de CIs (Passo a Passo):**',
      '1. **Isolamento e Proteção:** Proteja a área ao redor do CI com fita Kapton e blindagens metálicas.',
      '2. **Remoção do CI:** Aplique fluxo e use a estação de ar quente em movimentos circulares para remover o chip da placa.',
      '3. **Limpeza Profunda:** Limpe toda a resina e solda antiga tanto da placa quanto do CI usando malha dessoldadora e álcool isopropílico. A superfície deve ficar perfeitamente plana.',
      '4. **Aplicação do Stencil:** Posicione o stencil específico para o CI e aplique a pasta de solda, preenchendo todas as aberturas uniformemente.',
      '5. **Formação das Esferas:** Aqueça o CI com a pasta de solda para que as novas esferas (balls) se formem perfeitamente.',
      '6. **Ressoldagem na Placa:** Aplique fluxo na placa, posicione o CI alinhando-o com a marcação guia e aqueça novamente até que ele se "assente" na posição correta.',
      '**Como Reconstruir Trilhas Rompidas (Jumper):**',
      '1. **Identificação do Dano:** Use o microscópio para localizar a trilha ou pad rompido.',
      '2. **Raspagem Técnica:** Com um bisturi, raspe cuidadosamente a máscara de solda nas extremidades da trilha rompida para expor o cobre.',
      '3. **Aplicação de Fluxo e Estanho:** Aplique fluxo e estanhe as pontas de cobre expostas.',
      '4. **Criação da Ponte (Jumper):** Use um fio de cobre esmaltado bem fino para criar uma ponte entre os dois pontos. Solde o fio no lugar.',
      '5. **Isolamento e Cura:** Aplique máscara de solda UV sobre o jumper para isolá-lo e protegê-lo. Use uma lâmpada UV para curar a máscara, solidificando o reparo.',
    ],
  },
  {
    id: 'software',
    title: 'Software e Desbloqueio',
    description: 'Resolva problemas de software, remova contas Google e realize atualizações e downgrades de sistema.',
    longDescription: 'Nem todo defeito está no hardware. Muitas vezes, um celular travado, em loop infinito ou com falhas de aplicativo tem origem no sistema operacional. Este módulo é crucial e ensina a diagnosticar e resolver esses problemas de software, desde um simples reset de fábrica até procedimentos complexos como a reinstalação do sistema (ROM) e a remoção da conta Google (FRP), um dos serviços mais procurados.',
    icon: SoftwareIcon,
    topics: [
      '**Hard Reset (Formatação):**',
      'É o primeiro passo para resolver problemas de lentidão, travamentos e loops de inicialização. Aprenda a acessar o modo de recuperação (Recovery Mode) de diferentes marcas para apagar todos os dados e restaurar o sistema ao estado de fábrica.',
      '**Instalação de ROM (Flashing):**',
      'Quando o Hard Reset não resolve, a reinstalação completa do sistema (ROM) é a solução. Este guia ensina:',
      '1. **Download:** Encontrar a ROM correta (Stock ROM) para o modelo e versão do aparelho.',
      '2. **Drivers:** Instalar os drivers USB corretos no seu computador.',
      '3. **Ferramentas:** Usar programas específicos como Odin (para Samsung) ou ADB/Fastboot (para a maioria dos Androids).',
      '4. **Processo:** Colocar o celular em "Modo Download" ou "Fastboot" e executar o processo de flash para instalar o sistema do zero.',
      '**Remoção de Conta Google (FRP - Factory Reset Protection):**',
      'Após um Hard Reset, muitos aparelhos pedem a conta Google anterior. Este tópico aborda as técnicas para remover essa proteção quando o cliente esquece os dados, utilizando ferramentas de software específicas e métodos que variam conforme a marca e a versão do Android.',
      '**Backup e Restauração de Dados:**',
      '**IMPORTANTE:** Antes de qualquer procedimento de software, é fundamental tentar fazer o backup dos dados do cliente. Aprenda os métodos possíveis para salvar contatos, fotos e arquivos, mesmo quando o aparelho não liga completamente.',
    ],
  },
  {
    id: 'ios',
    title: 'Especialista em iPhones',
    description: 'Mergulhe no ecossistema Apple. Reparos e particularidades dos iPhones, do 7 ao mais recente.',
    longDescription: 'Entrar no universo Apple é um diferencial competitivo. O iPhone, com seu ecossistema fechado e arquitetura única, exige conhecimento especializado que a maioria dos técnicos generalistas não possui. Este módulo foca nas particularidades dos reparos de iPhones, desde a desmontagem cuidadosa até a solução de problemas complexos como falhas de Face ID e a programação da função True Tone após a troca de tela. Dominar essas técnicas coloca você em um patamar superior, pronto para atender uma clientela exigente e disposta a pagar mais por um serviço de excelência.',
    icon: IosIcon,
    topics: [
        '**Arquitetura e Desmontagem Específica:**',
        'Aprenda a lidar com parafusos Pentalobe, a técnica de abertura correta para não danificar os frágeis cabos do Face ID e a importância de mapear todos os parafusos, pois tamanhos diferentes em locais errados podem danificar a placa-mãe.',
        '**Reparo de Face ID e Touch ID:**',
        'Entenda por que esses componentes são "casados" com a placa-mãe. Saiba o que pode ser reparado (como o flex do iluminador) e o que leva à perda da função, permitindo que você dê um diagnóstico preciso ao seu cliente.',
        '**Preservação da Função True Tone:**',
        'A troca de tela em um iPhone não é apenas substituir a peça. Aprenda a usar programadoras (como Qianli ou JCID) para ler os dados da tela original e escrevê-los na nova, mantendo a função True Tone e entregando um serviço profissional.',
        '**Diagnóstico com 3uTools e Análise de Pânico:**',
        'Domine o 3uTools, um software essencial para verificar a autenticidade dos componentes e diagnosticar falhas. Aprenda a ler os relatórios de "Panic Full" (pânico total), que são logs de erro que apontam diretamente para o hardware defeituoso.',
        '**Falhas Comuns por Modelo:**',
        'Estude os defeitos crônicos: a "doença do áudio" no iPhone 7/7 Plus (falha no CI de áudio), problemas no "sanduíche" de placas do iPhone X e falhas de backlight comuns em diversos modelos. Saber disso acelera o diagnóstico.',
    ]
  },
  {
    id: 'android',
    title: 'Especialista em Androids',
    description: 'Domine a vasta gama de aparelhos Android, incluindo Samsung, Motorola, Xiaomi e outros.',
    longDescription: 'O universo Android é um gigante fragmentado, e é exatamente essa diversidade que cria uma enorme oportunidade para técnicos especializados. Diferente do ecossistema unificado da Apple, cada fabricante — Samsung, Motorola, Xiaomi e outros — possui suas próprias peculiaridades de hardware e software. Este módulo aprofundado prepara você para navegar nesse cenário complexo, ensinando a lidar com as telas AMOLED da Samsung, a arquitetura robusta da Motorola e os desafios de software da Xiaomi. Dominar o Android significa estar preparado para a grande maioria dos aparelhos do mercado, um diferencial indispensável para qualquer assistência técnica de sucesso.',
    icon: AndroidIcon,
    topics: [
      '**Diferenças Cruciais entre Fabricantes:**',
      'Entenda as particularidades: telas AMOLED e a complexidade das placas da Samsung; a arquitetura mais simples e o software "puro" da Motorola; e os desafios de software e componentes da Xiaomi.',
      '**Reparo de Telas com Borda Curva (Edge):**',
      'Domine a técnica de remoção e colagem de telas curvas, um dos serviços mais delicados e lucrativos em aparelhos premium da Samsung. Aprenda a usar as ferramentas corretas e a evitar danos no display durante o processo.',
      '**Desbloqueio de Bootloader e Software Avançado:**',
      'Vá além do Hard Reset. Aprenda a desbloquear o bootloader, um passo essencial para instalar ROMs customizadas, fazer root e resolver problemas de software que ferramentas comuns não alcançam.',
      '**Particularidades de Software (MIUI, One UI, etc.):**',
      'Resolva problemas específicos de cada sistema customizado. Lide com bugs comuns da MIUI (Xiaomi), remova apps pré-instalados (bloatware) da One UI (Samsung) e otimize o desempenho de diferentes versões do Android.',
      '**Fontes de Peças e Esquemas Elétricos:**',
      'Descubra como encontrar fornecedores de peças de reposição de qualidade para a vasta gama de modelos Android e onde acessar esquemas elétricos para diagnósticos avançados em placas.',
    ]
  },
];