
import { 
  ToolsIcon, 
  ScreenIcon, 
  BatteryIcon, 
  MotherboardIcon, 
  SolderingIcon, 
  SoftwareIcon,
  IosIcon,
  AndroidIcon,
  ConnectorIcon
} from './components/IconComponents';
import type { Course } from './types';

export const courses: Course[] = [
  {
    id: 'intro',
    title: 'Introdução e Ferramentas',
    description: 'Comece sua jornada com o pé direito. Conheça as ferramentas essenciais e os conceitos básicos de segurança.',
    longDescription: 'Bem-vindo ao ponto de partida da sua jornada como técnico de manutenção de celulares. Este módulo inicial foi desenhado para desmistificar o processo de reparo, apresentando os conceitos fundamentais de segurança e a organização de uma bancada de trabalho eficiente. Você entenderá a importância de cada passo, desde a correta identificação dos problemas até a execução dos procedimentos com precisão e segurança, garantindo a integridade dos aparelhos e a sua.',
    icon: ToolsIcon,
    topics: [
      'Kit de Chaves de Precisão: Indispensável para abrir os parafusos específicos de cada marca, como Philips, Pentalobe (iPhone) e Torx.',
      'Espátulas Plásticas e Metálicas: Utilizadas para abrir carcaças e desconectar componentes delicados sem causar arranhões ou danos.',
      'Ventosa de Sucção: Ferramenta chave para remover telas de vidro com segurança, aplicando uma força de tração uniforme.',
      'Estação de Ar Quente (Retrabalho): Essencial para dessoldar e soldar componentes na placa-mãe, como conectores de carga e CIs.',
      'Fonte de Alimentação Assimétrica: Permite ligar a placa-mãe sem a bateria para diagnosticar curtos-circuitos e analisar o consumo de energia.',
      'Multímetro Digital: Ferramenta de diagnóstico fundamental para medir voltagem, corrente e continuidade em circuitos eletrônicos.',
      'Pinças de Precisão (Reta e Curva): Usadas para manipular componentes minúsculos, parafusos e cabos flexíveis com exatidão.',
      'Manta Antiestática (ESD): Protege os componentes eletrônicos sensíveis contra danos por descarga eletrostática durante o manuseio.',
      'Pulseira e Luvas Antiestáticas (ESD): Equipamento de proteção pessoal que aterra o técnico para evitar que a eletricidade estática do corpo danifique o aparelho.',
      'Álcool Isopropílico: O solvente ideal para limpar placas de circuito e componentes eletrônicos, pois evapora rapidamente sem deixar resíduos.',
      'Microscópio USB ou Estereoscópio: Amplia a visão da placa-mãe, permitindo a execução de micro-soldagens e a inspeção de componentes minúsculos.',
      'Cuba Ultrassônica para Desoxidação: Utilizada com produtos químicos específicos para remover a oxidação de placas que tiveram contato com líquidos.',
    ],
  },
  {
    id: 'screen',
    title: 'Reparo de Telas e Displays',
    description: 'Aprenda a trocar telas quebradas de diversos modelos, dos mais simples aos mais complexos.',
    longDescription: 'Um dos serviços mais comuns e lucrativos na manutenção de celulares. Este módulo foca em todo o processo de substituição de telas, desde a avaliação inicial até os testes finais. Você aprenderá as técnicas corretas para lidar com diferentes tecnologias de display, como LCD e OLED, e os cuidados necessários para realizar um trabalho limpo e profissional, garantindo a satisfação total do seu cliente.',
    icon: ScreenIcon,
    topics: [
      'Diagnóstico Inicial: Antes de desmontar, teste todas as funções do aparelho (câmeras, microfone, botões) para garantir que o único problema é a tela.',
      'Preparação da Bancada: Organize suas ferramentas e utilize uma manta magnética para não perder os parafusos. Tenha a tela nova em mãos para comparação.',
      'Aquecimento e Abertura: Aqueça as bordas do aparelho (entre 80-100°C) com uma estação de ar quente ou separadora para amolecer a cola. Use uma ventosa e espátulas plásticas para abrir o chassi com cuidado.',
      'Desconexão de Componentes: Desconecte a bateria primeiro para evitar curtos-circuitos. Em seguida, com cuidado, desconecte os cabos flexíveis (flex cables) da tela, biometria e outros sensores.',
      'Remoção da Tela Antiga: Com o aparelho aberto, remova cuidadosamente a tela danificada. Limpe toda a cola antiga e resíduos de vidro do chassi para garantir um encaixe perfeito da nova tela.',
      'Teste da Tela Nova (Pré-colagem): Conecte a nova tela temporariamente (sem colar) e ligue o aparelho. Teste o touch em toda a superfície, as cores, o brilho e a resposta do display.',
      'Colagem e Montagem: Após o teste, aplique a cola específica (como B-7000 ou T-7000) nas bordas do chassi. Encaixe a nova tela, reconecte todos os cabos e a bateria.',
      'Fechamento e Testes Finais: Feche o aparelho, coloque os parafusos e utilize presilhas ou elásticos para pressionar a tela enquanto a cola seca (por pelo menos 4 horas). Realize um teste completo de todas as funções novamente.',
    ],
  },
  {
    id: 'battery',
    title: 'Troca e Diagnóstico de Bateria',
    description: 'Domine a arte de substituir baterias e diagnosticar problemas de carregamento e autonomia.',
    longDescription: 'Baterias são o coração energético do celular, mas têm uma vida útil limitada. Este módulo essencial ensina tudo sobre elas: desde identificar os sinais de uma bateria cansada ou defeituosa até o procedimento de troca seguro e eficaz. Domine esta habilidade crucial e resolva um dos problemas mais frequentes enfrentados pelos usuários.',
    icon: BatteryIcon,
    topics: [
      '**Como Trocar a Bateria (Passo a Passo):**',
      '1. **Diagnóstico:** Verifique a "Saúde da Bateria" nas configurações (iOS) ou use apps de diagnóstico (Android) para confirmar a necessidade da troca.',
      '2. **Abertura do Aparelho:** Aqueça a tampa traseira para amolecer o adesivo. Use ventosas e espátulas para abrir o dispositivo com cuidado.',
      '3. **Desconexão Segura:** A primeira coisa a fazer é desconectar o cabo flex da bateria da placa-mãe para desenergizar o circuito e evitar curtos.',
      '4. **Remoção da Bateria Antiga:** As baterias são fixadas com adesivos fortes. Use álcool isopropílico para dissolver a cola e uma espátula plástica (nunca de metal) para removê-la com cuidado, sem dobrar ou perfurar.',
      '5. **Instalação e Fechamento:** Limpe a área, aplique novas fitas adesivas, posicione a nova bateria, conecte-a e monte o aparelho.',
      '6. **Calibração:** Após a troca, use o celular até a bateria descarregar completamente e depois realize uma carga completa até 100% sem interrupções.',
      '**Principais Defeitos e Dicas:**',
      '- **Bateria Estufada:** Sinal de falha grave. Causa pressão na tela e na carcaça. Remova com extremo cuidado, pois há risco de incêndio se perfurada.',
      '- **Desligamentos Súbitos:** O celular desliga mesmo com carga (ex: 30-40%). A bateria não consegue mais fornecer a corrente necessária.',
      '- **Não Carrega ou Carregamento Lento:** Antes de culpar a bateria, sempre teste com outro cabo e carregador. O defeito também pode ser no conector de carga.',
      '- **Superaquecimento:** Baterias defeituosas podem esquentar excessivamente. A troca é uma medida de segurança para evitar danos a outros componentes.',
    ],
  },
  {
    id: 'motherboard',
    title: 'Diagnóstico de Placa-mãe',
    description: 'Aprenda a ler esquemas elétricos e a diagnosticar defeitos complexos na placa-mãe.',
    longDescription: 'Entre no nível mais avançado da manutenção. A placa-mãe é o cérebro do celular, e entender seu funcionamento é o que diferencia um técnico comum de um especialista. Este módulo ensina a diagnosticar e reparar falhas em nível de componente, abrindo portas para os consertos mais desafiadores e lucrativos.',
    icon: MotherboardIcon,
    topics: [
      '**Principais Defeitos e Diagnósticos:**',
      '- **Curto-circuito:** Identifique a causa do consumo excessivo de corrente usando a fonte de alimentação e técnicas de congelamento (breu) ou câmera térmica.',
      '- **Danos por Líquido (Oxidação):** Aprenda o processo correto de desoxidação com cuba ultrassônica e a identificar componentes corroídos que precisam ser substituídos.',
      '- **Aparelho Não Liga:** Siga uma linha de diagnóstico, verificando o botão power, o circuito de carga (PMIC) e as tensões primárias.',
      '- **Falhas de Backlight (Tela Escura):** Analise o circuito que alimenta a iluminação da tela, incluindo o CI de backlight, diodos e bobinas.',
      '**Como Trocar Componentes (Micro-soldagem):**',
      '1. **Isolamento da Área:** Proteja os componentes ao redor do alvo com fita Kapton (resistente ao calor) para evitar danos.',
      '2. **Aplicação de Fluxo:** Aplique fluxo de solda de boa qualidade sobre o componente. Isso ajuda na transferência de calor e evita a oxidação.',
      '3. **Dessoldagem (Ar Quente):** Com a estação de ar quente (aprox. 380-420°C), aqueça o componente em movimentos circulares até a solda fundir. Remova-o com uma pinça.',
      '4. **Limpeza dos Pads:** Com a malha dessoldadora e o ferro de solda, remova a solda antiga dos contatos (pads) na placa. Limpe a área com álcool isopropílico.',
      '5. **Soldagem do Novo Componente:** Posicione o novo componente e aqueça novamente com a estação de ar quente até que ele se "assente" nos pads. Dê um leve toque para confirmar a fusão.',
      '6. **Inspeção Final:** Após esfriar, inspecione a solda com um microscópio para garantir que não há curtos. Limpe o fluxo residual.',
    ],
  },
  {
    id: 'connectors',
    title: 'Reparo de Conectores',
    description: 'Especialize-se na troca de conectores de carga, fone de ouvido e outros componentes.',
    longDescription: 'Problemas de carregamento são uma das queixas mais comuns. Dominar a troca de conectores (USB-C, Lightning, Micro-USB) é uma habilidade essencial e altamente rentável. Este módulo ensina as técnicas de micro-soldagem necessárias para realizar um trabalho limpo e duradouro, garantindo que o aparelho do cliente volte a carregar e transferir dados perfeitamente.',
    icon: ConnectorIcon,
    topics: [
      '**Como Trocar Conectores (Passo a Passo):**',
      '1. **Diagnóstico:** Antes de tudo, limpe o conector com uma escova e álcool isopropílico. Teste com um cabo e carregador sabidamente bons. O problema pode ser sujeira ou um acessório defeituoso.',
      '2. **Proteção:** Isole a área ao redor do conector com fita Kapton. Isso protegerá microfones, plásticos e outros componentes sensíveis do calor da estação de ar quente.',
      '3. **Facilitando a Remoção:** Aplique fluxo de solda e um pouco de solda de baixa fusão (como 183°C) sobre os pinos do conector antigo. Isso ajuda a remover o componente sem exigir calor excessivo na placa.',
      '4. **Dessoldagem:** Use a estação de ar quente por baixo da placa (se possível) ou por cima com cuidado. Aqueça a área até a solda brilhar e remova o conector defeituoso com uma pinça.',
      '5. **Limpeza e Preparação:** Com malha dessoldadora, remova toda a solda antiga dos pads (pontos de contato). Limpe a área com álcool isopropílico para não deixar nenhum resíduo.',
      '6. **Estanhagem dos Pads:** Aplique fluxo e passe um pouco de solda nova em cada pad na placa. Isso prepara a base para receber o novo componente.',
      '7. **Soldagem do Novo Conector:** Posicione o novo conector. Solde primeiro os pinos de ancoragem (laterais) para fixá-lo. Depois, com um ferro de solda de ponta fina, solde cada um dos pinos de dados e energia individualmente.',
      '8. **Inspeção e Teste Final:** Com um microscópio, verifique se não há curtos entre os pinos. Faça uma limpeza final. Antes de fechar o aparelho, conecte uma bateria e um cabo para testar se o carregamento e a transferência de dados estão funcionando.',
    ]
  },
  {
    id: 'microsoldering',
    title: 'Micro-soldagem Avançada',
    description: 'Leve suas habilidades ao próximo nível com técnicas de micro-soldagem para reparos em nível de componente.',
    longDescription: 'Para os defeitos mais complexos, a micro-soldagem é essencial. Aprenda a manusear o microscópio, a estação de ar quente e o ferro de solda de precisão para trocar CIs (Circuitos Integrados), realizar reballing e reconstruir trilhas danificadas na placa.',
    icon: SolderingIcon,
    topics: [
      'Uso de microscópio para reparos',
      'Técnicas de reballing de CIs',
      'Troca de componentes SMD',
      'Reconstrução de pads e trilhas',
      'Uso de malha dessoldadora e fluxo de solda',
    ],
  },
  {
    id: 'software',
    title: 'Software e Desbloqueio',
    description: 'Resolva problemas de software, remova contas Google e realize atualizações e downgrades de sistema.',
    longDescription: 'Nem todo problema é de hardware. Este módulo foca em resolver falhas de software, como loops de inicialização, remoção de conta Google (FRP), instalação de ROMs customizadas e procedimentos de flash para recuperar aparelhos travados.',
    icon: SoftwareIcon,
    topics: [
      'Instalação de ROMs (Stock e Custom)',
      'Remoção de Conta Google (FRP)',
      'Procedimentos de Hard Reset',
      'Uso de ferramentas como Odin e ADB',
      'Backup e restauração de dados',
    ],
  },
  {
    id: 'ios',
    title: 'Especialista em iPhones',
    description: 'Mergulhe no ecossistema Apple. Reparos e particularidades dos iPhones, do 7 ao mais recente.',
    longDescription: 'O iPhone tem uma arquitetura única que exige conhecimento especializado. Este curso detalha os procedimentos de reparo específicos para cada modelo, desde a troca de tela com True Tone até o diagnóstico de falhas comuns como o "erro de áudio" e problemas na baseband.',
    icon: IosIcon,
    topics: [
        'Arquitetura e desmontagem de iPhones',
        'Reparo de Face ID e Touch ID',
        'Preservação da função True Tone',
        'Diagnóstico com 3uTools',
        'Falhas comuns por modelo',
    ]
  },
  {
    id: 'android',
    title: 'Especialista em Androids',
    description: 'Domine a vasta gama de aparelhos Android, incluindo Samsung, Motorola, Xiaomi e outros.',
    longDescription: 'O universo Android é diverso. Aprenda as particularidades de cada grande fabricante, como as telas AMOLED da Samsung, a arquitetura da Motorola e os desafios dos aparelhos Xiaomi. Este curso prepara você para lidar com a enorme variedade do mercado.',
    icon: AndroidIcon,
    topics: [
        'Diferenças entre fabricantes',
        'Reparo de telas com borda curva (Edge)',
        'Desbloqueio de bootloader',
        'Particularidades de software (MIUI, One UI)',
        'Fontes de peças para diversas marcas',
    ]
  },
];